import { Container, Grid, Stack } from "@mui/material";
import Doctor from "components/cards/Doctor";
import MainLayout from "components/layout/main";
import { MainHeader } from "components/styled";
import { doctors } from "data/doctors";
import Head from "next/head";
import React from "react";

const Page = () => {
  return (
    <>
      <Head>
        <title>Shifokorlar</title>
        <meta name="robots" content="all" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Stack bgcolor="background.header" mb="24px">
          <Container>
            <MainHeader lineHeight="156px" my="40px">
              Shifokorlar
            </MainHeader>
          </Container>
        </Stack>
        <Container>
          <Grid container>
            {doctors.map((item, index) => (
              <Grid item xs={12} sm={12} md={4} mb="30px">
                <Doctor {...item} isSelected={[1, 4, 7].includes(index)} />
              </Grid>
            ))}
          </Grid>
        </Container>
      </MainLayout>
    </>
  );
};

export default Page;
