import { Container, Stack } from "@mui/material";
import CustomPagination from "components/CustomPagination";
import Clinics from "components/cards/Clinics";
import MainLayout from "components/layout/main";
import { MainHeader } from "components/styled";
import { clinics } from "data/clinics";
import Head from "next/head";
import React from "react";

const Page = () => {
  return (
    <>
      <Head>
        <title>Klinikalar</title>
        <meta name="robots" content="all" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Stack bgcolor="background.header" mb="24px">
          <Container>
            <MainHeader lineHeight="156px" my="40px">
              Klinikalar
            </MainHeader>
          </Container>
        </Stack>
        <Container>
          {[...clinics, ...clinics, ...clinics].map((clinic) => (
            <Clinics key={clinic.id} {...clinic} />
          ))}

          <CustomPagination />
        </Container>
      </MainLayout>
    </>
  );
};

export default Page;
