import Head from "next/head";
import { Inter } from "next/font/google";
import MainLayout from "components/layout/main";
import HeaderComponent from "components/HeaderComponent";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Med Care</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <HeaderComponent
          name="Shifokorlarimiz"
          link="/topics"
        ></HeaderComponent>
        <HeaderComponent name="Maqolalar" link="/topics"></HeaderComponent>
        <HeaderComponent name="Maqolalar" link="/topics"></HeaderComponent>
      </MainLayout>
    </>
  );
}
